name: release-bib

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 1 * * 0"

jobs:
  release-bib:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Download usenix.bib
        run: wget -O usenix.bib https://www.usenix.org/biblio/export/bibtex
        
      - name: Download usenix.bib.old
        run: |
          wget -O usenix.bib.old https://github.com/Pusnow/usenix.bib/releases/latest/download/usenix.bib || true

      - name: Diff files
        run: |
          diff usenix.bib usenix.bib.old || touch changed
          
          
      - name: Make version file
        run: |
          date '+%Y-%m-%d' > version.txt

      - name: Create release
        run: |
          if [ -f changed ]; then gh release create -t $(cat version.txt) -F version.txt $(cat version.txt) usenix.bib version.txt; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update bib
        run: |
          if [ -f changed ]; then python3 scripts/split-bib.py &&\
            git config --local user.email "wonsup@pusnow.com" &&\
            git config --local user.name "Wonsup Yoon" &&\
            git add bib &&\
            git commit -m "[bib] $(cat version.txt)" &&\
            git push; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
